### ISSUE TITLE
DFD Comments 2/21 (2)

### ISSUE THREAD

**Issue by germonprez** [Saeed19/ISQA3420-1#14]
You did not fix this from the earlier issue: 

Names like Request Information and Retrieve Information (along with some of the dataflows) are far too vague. The names need to be considerably more specific

You have some Dataflow naming conventions that need to be fixed (e.g., Software Vuln&License -- is this the same as Request Information?)

You have an arrow pointing the wrong way coming out of the Manage Software Package process

**Comment by Saeed19** [comment]
Changed
