### ISSUE TITLE
DFD Comments Feb 16

### ISSUE THREAD

**Issue by germonprez** [Saeed19/ISQA3420-1#6]
Here are a few comments: 

1) You also need to send license results to the DB here - 

<img width="350" alt="screen shot 2017-02-16 at 5 34 04 am" src="https://cloud.githubusercontent.com/assets/656208/23023287/a5f72b38-f409-11e6-95cc-6ae403b1aa4c.png">

2) The Developer will not request policies. The Developer will request license and vulnerability information from the L&V database. The Developer needs to connect to this process: 

<img width="412" alt="screen shot 2017-02-16 at 5 36 21 am" src="https://cloud.githubusercontent.com/assets/656208/23023331/e37aee86-f409-11e6-956b-240f7e6300eb.png">

3) Likewise, on this process, are Software Package Vulnerability Result and License and Vulnerability Results the same thing? If so, they should have the same name: 

<img width="412" alt="screen shot 2017-02-16 at 5 36 21 am" src="https://cloud.githubusercontent.com/assets/656208/23023345/07266202-f40a-11e6-89c4-a4897c400348.png">

4) Policy Info and Policy Request can be removed from this: 

<img width="89" alt="screen shot 2017-02-16 at 5 38 13 am" src="https://cloud.githubusercontent.com/assets/656208/23023379/2c9b84e0-f40a-11e6-99c0-dec5a7e198f1.png">

**Comment by Saeed19** [comment]
Updated as DFD Saeed v2
